branch-defaults:
  awsl2:
    environment: contract-al2-hgapp
    group_suffix: null
  default:
    environment: Default-Environment
  master:
    environment: Hgapp-env-contract
    group_suffix: null
environment-defaults:
  Default-Environment:
    branch: null
    repository: null
global:
  application_name: hgapp
  branch: null
  default_ec2_keyname: mcserv
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
